version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: feirai_backend
    ports:
      - "3005:3005"
    volumes:
      - ./server/data/feirai.sqlite:/app/feirai.sqlite
      - /mnt/d/Nuvem/Dropbox/Backups/apps/feirai:/app/backups
    environment:
      - DB_PATH=${DB_PATH:-/app/feirai.sqlite}
      - NODE_ENV=${NODE_ENV:-production}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: feirai_frontend
    ports:
      - "3010:80"
    depends_on:
      - backend
    restart: unless-stopped
